name: Python application

on:
  push:
    branches: [ "master" ]
    
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install awscli
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token:  ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: "us-east-1"
    - name: Actualiza etapas
      run: |
        zappa update dev
        zappa update dev2
    - name: Prueba
      run: |
        zappa invoke dev descargar.lambda1